name: nightly.yml

on:
  schedule:
    - cron:  '30 0 * * *' #< runs daily at 00:30 am
jobs:
  deploy:
    if: github.repository == 'google-research/kubric'  # prevents action from running on forks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install packaging requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U packaging
        pip install -U setuptools
        pip install -U wheel
        pip install -U twine
    
    - name: Build package and upload to test.pypi
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel --nightly
        twine check dist/*
        twine upload --repository testpypi dist/*
