name: pypi.yml

on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    if: github.repository == 'google-research/kubric'  # prevents action from running on forks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U -r requirements.txt
        pip install -U setuptools
        pip install -U twine